### PR TITLE
Fix renderstate fields disappearing when sessions created without layers

### LINKED ISSUE #18: XRSession `baseLayer` is null in renderState if created with no layers in WebXR emulator
#11 modifies the renderState if the polyfill has not handled any layers and adds an empty `layers: []` array to the renderState. However, with how the renderState is implemented in the WebXR emulator (and possibly in browsers), this causes all other fields of renderState to no longer be accessible.

Notably, at time of writing, the projection-multiview example in the repository is broken since it relies upon reading `session.renderState.baseLayer` in the non-immersive context.

### PR DESCRIPTION
**Pull request by dmliao**
This fixes #18 and addresses some other issues with renderState, namely:

1. the `activeRenderState` variable that the polyfill maintains in the session was not merging with prior versions, so it was possible to end up losing fields if `updateRenderState` was called multiple times. This should now be fixed.
2. If a session was created with the polyfill active and no layers array, a new `renderState` object was being created every time `session.renderState` was called, which could be per-frame. This changes that so now the new `renderState` object is only created when `updateRenderState` is called, or when queried for the first time.

### CODE REVIEW

File: src/api/XRSessionWithLayer.ts [hunk 1]
```diff
@@ -277,18 +277,24 @@ export class XRSessionWithLayer {
...
-			// just go on without doing anything
-			return (this as any)._updateRenderState(XRRenderStateInit)
+		this.layers = XRRenderStateInit.layers || []
+
+		if (!this.activeRenderState) {
+			this.createActiveRenderState()
 		}
 
-		this.layers = XRRenderStateInit.layers || []
+		this.activeRenderState = { ...this.activeRenderState, ...XRRenderStateInit }
```
Comment (cabanier) [inline src/api/XRSessionWithLayer.ts:289]: wow. fancy!

**Review by cabanier — APPROVED** [review]
